version: "3"
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: aejimeongji
      MYSQL_ROOT_PASSWORD: dowlajdwl1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: dowlajdwl1234
    ports:
      - 3306:3306
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
      - ./database/datadir/:/var/lib/mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    expose:
      - 3306

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/var/lib/mysql
    expose:
      - 6379

  springbootapp:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - /images:/images
    depends_on:
      - mysql
      - redis
    expose:
      - 8080